import Footer from "@/comoponents/footer";
import Header from "@/comoponents/header";
import Loader from "@/comoponents/loader";
import type { Metadata } from "next";
import localFont from "next/font/local";
import ClientWrapper from "@/comoponents/clientWrapper";
import Head from "next/head";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Elila foundation",
  description: "Generated by create next app",
  icons: {
    icon: "/ELILA FOUNDATION WHITE.png" as string,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <Head>
        <title>{metadata.title ? String(metadata.title) : "Titre par défaut"}</title>
        <meta name="description" content={metadata.description ?? "Description par défaut"} />
        <link rel="icon" href={typeof metadata.icons === 'string' ? metadata.icons : (Array.isArray(metadata.icons) ? String(metadata.icons[0]) : "/default-icon.png")} />     </Head>
      <body className={`index-page ${geistSans.variable} ${geistMono.variable}`}>
        <ClientWrapper>
          <Header />
          <Loader />
          {children}
          <Footer />
        </ClientWrapper>
      </body>
    </html>
  );
}
